### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/infer_structcol#18]
Running `nosetests -v` in the root directory gives me the following output:

infer_structcol.tests.test_io.test_io ... ok
infer_structcol.tests.test_main.test_Spectrum ... ok
infer_structcol.tests.test_main.test_Sample ... ok
infer_structcol.tests.test_main.test_extend_array ... ok
infer_structcol.tests.test_main.test_rescale ... ok
infer_structcol.tests.test_main.test_find_close_indices ... ok
infer_structcol.tests.test_model.test_prior ... ok
infer_structcol.tests.test_model.test_likelihood ... ok
infer_structcol.tests.test_model.test_log_posterior ... C:\Users\vnm\Anaconda3\lib\site-packages\pint\quantity.py:761: RuntimeWarning: divide by zero encountered in double_scalars
  return self.__class__(other_magnitude / self._magnitude, 1 / self._units)
FAIL
infer_structcol.tests.test_run_structcol.test_structcol_import ... ok
infer_structcol.tests.test_run_structcol.test_run_structcol ... FAIL
structcol.tests.test_mie.test_cross_sections ... ok
structcol.tests.test_mie.test_form_factor ... ok
structcol.tests.test_mie.test_efficiencies ... ok
structcol.tests.test_mie.test_absorbing_materials ... ok
structcol.tests.test_model.test_fresnel ... ok
structcol.tests.test_refractive_index.test_n ... ok
structcol.tests.test_refractive_index.test_water ... ok
structcol.tests.test_refractive_index.test_npmma ... ok
structcol.tests.test_refractive_index.test_nps ... ok
structcol.tests.test_refractive_index.test_rutile ... ok
structcol.tests.test_refractive_index.test_fused_silica ... ok
structcol.tests.test_refractive_index.test_vacuum ... ok
structcol.tests.test_structcol.test_q ... ok
structcol.tests.test_structure.test_structure_factor_percus_yevick ... ok

======================================================================
FAIL: infer_structcol.tests.test_model.test_log_posterior
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\tests\test_model.py", line 30, in test_log_posterior
    assert_approx_equal(post, -1.219450433033298)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 637, in assert_approx_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal to 7 significant digits:
 ACTUAL: 1.347804716961792
 DESIRED: -1.219450433033298

======================================================================
FAIL: infer_structcol.tests.test_run_structcol.test_run_structcol
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\tests\test_run_structcol.py", line 30, in test_run_structcol
    assert_almost_equal(spectrum.reflectance, outarray, decimal=5)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 523, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 918, in assert_array_almost_equal
    precision=decimal)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 5 decimals

(mismatch 100.0%)
 x: array([ 0.59395,  0.56222])
 y: array([ 0.36429,  0.32796])

----------------------------------------------------------------------
Ran 25 tests in 6.912s

FAILED (failures=2)

**Comment by barkls** [comment]
The test values had been set with a previous version of structcol. Reinstalling a fresh copy and resetting the expected values to the ones you got fixed the problem.

**Comment by vnmanoharan** [comment]
It's not clear why you would want to reset the expected values to the ones I got.  Tests should be written so that the output of the test is compared to a known value; if you compare the output of the test to the output of the test, you're not really testing anything.

**Comment by tessadgreen** [comment]
Tests are failing with an import error:

ERROR: Failure: ImportError (No module named 'structcol')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "//anaconda/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "//anaconda/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "//anaconda/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "//anaconda/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "//anaconda/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/tdgreen/GitHub/infer_structcol/infer_structcol/__init__.py", line 3, in <module>
    from .model import log_posterior, get_distribution, run_mcmc
  File "/Users/tdgreen/GitHub/infer_structcol/infer_structcol/model.py", line 6, in <module>
    from .run_structcol import calc_reflectance
  File "/Users/tdgreen/GitHub/infer_structcol/infer_structcol/run_structcol.py", line 4, in <module>
    import structcol as sc
ImportError: No module named 'structcol'

**Comment by barkls** [comment]
While this is generally true, in our case we are testing stochastic processes in the limit of small N (so that tests run quickly). As a result, the output is highly dependent on the random seed and cannot be computed theoretically. The tests were initially written using an out-of-date version of the structcol package. We have to rely on any updates to this package maintaining a correct result. However, any changes to how this external package calls numpy.random would be expected to alter our test results, even with a fixed seed. Evidently, the most recent update to structcol did change the output returned, even with the same inputs (including fixed random seed value). Is there a better way to test this type of situation?

**Comment by vnmanoharan** [comment]
It depends on what you are trying to test.  If you are just testing that the Monte Carlo runs, then you don't need a comparison value.  If you are testing for correctness of the MC run, then you need a value that you can verify using some other method (for example, an analytical result for a limiting case).  The dependence on the random number generator can be solved by using a fixed seed in the test or by reducing the precision of your comparison.

**Comment by barkls** [comment]
We would like to test against future changes to our code (infer_structcol) returning the same output for a given version of the structcol package. Ideally, we would obtain the same output even across different versions of structcol, but we don't have a good way of confirming that it's results won't have changed with an update.

**Comment by vnmanoharan** [comment]
It sounds like you need to (a) add a test to structcol for some set of parameters for which you know what the result should be; and (b) add a test to infer_structcol that shows that you recover those same parameters.

**Comment by barkls** [comment]
We don't have a test that actually runs inference and returns parameter values (since this would take a very long time), but we now have good regression test coverage in both packages.
