### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by ralex0** [p201-sp2016/infer_structcol#2]
Hey Rumps, 

The setup.py doesn't work for me. I cloned the directory to my computer and did `pip install .` in it. I see a couple typos, and that the install requires structural-color (which I know I don't currently have installed), I think the setup.py will still fail because structural-color is not on pip or the default conda repo (is it on conda-forge?)

I searched it, and saw that structural-color is another Manoharan Lab project, but there's no setup.py, so I can't install it so that the import statement in the test will work without jumping though some hoops...

So, I would recommend mentioning how to get structural-color in an install.txt or README, or including the source code from it in this package (I'm sure you have appropriate permission) and update the setup.py. (I guess I can't ask you to make a setup.py for structural-color haha.)

I'll submit another issue or update if I find something else, but it looks fine so far.

**Comment by ralex0** [comment]
Good news, [someone wrote a setup.py for structural color](https://github.com/manoharan-lab/structural-color/pull/21).

**Comment by ralex0** [comment]
One more quick note, I just learned that you can specify a GitHub repo in the requirements if the package is not on PyPI. [(link)](http://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi)

**Comment by victoriahwang89** [comment]
Added an explanation to the README file, saying that the user should download or git clone the structural-color package, and then copy the structcol directory into the root directory of the infer-structcol package. We also fixed a typo in setup.py. The package now seems to install correctly.
