### ISSUE TITLE
implement MAP finding routine

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/infer_structcol#23]
Before you go further on sampling, you should try to implement a routine to find the MAP (for example, by running Levenberg-Marquardt on the posterior).  That is a faster operation than sampling, and it will be useful for your sampling scheme: because model calculations are so expensive, you need to make sure your burn-in time is low and that your walkers equilibrate.  The best way to do that (assuming the posterior is monomodal) is to spread your walkers around the MAP.

**Comment by barkls** [comment]
Addressed in #28.
