### ISSUE TITLE
use parametric form for loss function

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/infer_structcol#4]
As we discussed, you should probably start by choosing a parametric form for your loss function.  Right now you have as many parameters as you have data points, making this a nonparametric problem (which will be more difficult to solve).  If you were interested in the values of the loss function, a nonparametric approach would make sense, but since you're not the best strategy is to choose a simple functional form for the loss function.

**Comment by barkls** [comment]
We are now using a linear model for losses as a function of wavelength. This has been updated in model.ipynb as well as model.py.
